# //////////////////////////////////////////////////////////////////////////////
from __future__ import annotations

import argparse
import bs4
import json
import logging
import os
import sys
import re
import typing
import html

from . import __version__ as current_version

from packaging.version import Version

# //////////////////////////////////////////////////////////////////////////////

g_log = logging.getLogger(__name__)


# //////////////////////////////////////////////////////////////////////////////


def check_extension(
    file_direaction: str,
    choices: typing.List[str],
) -> typing.Callable:
    assert type(file_direaction) is str
    assert type(choices) is list

    def mapper(filename):
        ext = os.path.splitext(filename)[1].lower()
        if ext in choices:
            return filename
        raise argparse.ArgumentTypeError(
            "Bad {} file extension: '{}'. It was expecting one from {}.".format(
                file_direaction,
                ext,
                choices,
            )
        )

    return mapper


# ------------------------------------------------------------------------
def parse_arguments() -> argparse.Namespace:
    command_parser = argparse.ArgumentParser(
        description="A tool to extract json data from pytest-html report.",
        epilog="Example: pgpro-pytest-html-json-extract -o report.json report.html",
    )

    command_parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {current_version}",
        help="Show program's version number and exit",
    )

    command_parser.add_argument(
        "--out",
        "-o",
        help="name of the output json file",
        type=check_extension("output", [".json"]),
        required=True,
    )

    command_parser.add_argument(
        "--replace",
        "-r",
        help="replace output if it exists",
        action="store_true",
    )

    command_parser.add_argument(
        "--no-check-json",
        dest="check_json",
        action="store_false",
        help="skip JSON format validation after extraction",
    )

    command_parser.add_argument(
        "--no-unescape-logs",
        dest="unescape_logs",
        action="store_false",
        help="do not unescape HTML entities in logs",
    )

    command_parser.add_argument(
        "--verbose",
        "-v",
        help="level of logging verbosity",
        default=3,
        action="count",
    )

    command_parser.add_argument(
        "input",
        help="html file generated by pytest-html",
        type=check_extension("input", [".html", ".htm"]),
    )

    return command_parser.parse_args()


class PytestHtmlJsonExtractor:
    C_MININAL_PYTEST_HTML_VERSION = "4.0.2"

    # --------------------------------------------------------------------
    @staticmethod
    def _extract_pytest_html_version(
        report_path,
        report_soup: bs4.BeautifulSoup,
    ) -> str:
        assert report_path is not None
        assert isinstance(report_soup, bs4.BeautifulSoup)

        """
        Robustly extract pytest-html version from the report footer/header.
        Example text: '... by pytest-html v4.0.2'
        """
        link = report_soup.find("a", href=re.compile(r"pytest-html"))
        if link is None:
            raise RuntimeError(
                "Report does not have section with pytest-html link.",
            )

        parent_text = link.parent.get_text()

        # Looking for pattern 'v' and digits (v4.0.2)
        match = re.search(r"v(\d+\.\d+\.\d+[\w\.]*)", parent_text)
        if not match:
            __class__._raise_err__cant_extract_report_version(
                report_path,
                parent_text,
            )

        return match.group(1)

    # --------------------------------------------------------------------
    @staticmethod
    def exec(
        input_path: str,
        check_json: bool,
        output_path: str,
        replace: bool,
        unescape_logs: bool = True,
    ):
        assert type(input_path) is str
        assert type(check_json) is bool
        assert type(output_path) is str

        g_log.info("Processing report: {}".format(input_path))

        with open(input_path, "r", encoding="utf-8") as f:
            soup = bs4.BeautifulSoup(f, features="html.parser")

        html_version = __class__._extract_pytest_html_version(
            input_path,
            soup,
        )
        assert type(html_version) is str

        min_version = Version(__class__.C_MININAL_PYTEST_HTML_VERSION)
        if Version(html_version) < min_version:
            __class__._raise_err__unsupported_html_version(
                input_path,
                html_version,
            )

        # load json data from the current report
        containers = soup.select("#data-container")
        if not containers:
            __class__._raise_err__json_blob_is_not_found(input_path)

        report_data_container = containers[0]

        jsonblob = report_data_container.get("data-jsonblob")

        # memory is freed
        del report_data_container
        del soup

        # ----------
        if jsonblob is None:
            __class__._raise_err__json_blob_is_not_found(
                input_path,
            )

        assert type(jsonblob) is str

        if unescape_logs:
            jsondata = json.loads(jsonblob)
            __class__._inplace_unescape_logs(jsondata)
            jsonblob = json.dumps(jsondata, ensure_ascii=False)
            del jsondata  # memory is freed

        if check_json:
            g_log.info("Json data is checked...")
            json.loads(jsonblob)

        # write to file
        write_mode = "w" if replace else "x"

        with open(output_path, write_mode, encoding="utf-8") as f:
            f.write(jsonblob)

        return

    # --------------------------------------------------------------------
    @staticmethod
    def _inplace_unescape_logs(jsondata: typing.Any) -> None:
        C_DATA_ELEMENT_ID__TESTS = "tests"
        C_DATA_ELEMENT_ID__LOG = "log"

        assert jsondata is not None

        g_log.debug("Html escapes in logs are unpacking ...")

        if type(jsondata) is not dict:
            return

        tests = jsondata.get(C_DATA_ELEMENT_ID__TESTS)

        if tests is None:
            return

        if type(tests) is not dict:
            return

        for _, test_launches in tests.items():
            if test_launches is None:
                continue

            if type(test_launches) is not list:
                continue

            for t in test_launches:
                if t is None:
                    continue

                if type(t) is not dict:
                    continue

                log_data = t.get(C_DATA_ELEMENT_ID__LOG)

                if log_data is None:
                    continue

                if type(log_data) is not str:
                    continue

                t[C_DATA_ELEMENT_ID__LOG] = html.unescape(log_data)
                continue
            continue
        return

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__no_section_with_version(report_path) -> typing.NoReturn:
        err_msg = "Report [{}] does not have section with pytest-html link.".format(  # noqa: E501
            report_path
        )
        raise RuntimeError(err_msg)

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__cant_extract_report_version(
        report_path,
        text,
    ) -> typing.NoReturn:
        assert report_path is not None
        err_msg = "Cannot extract pytest-html version from {0!r}. Source file is [{1}]".format(  # noqa: E501
            text,
            report_path,
        )
        raise RuntimeError(err_msg)

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__unsupported_html_version(
        report_path: str,
        version: str,
    ) -> typing.NoReturn:
        assert report_path is not None
        assert type(version) is str
        err_msg = "Source file [{}] has an unsupported version [{}]. The minimal supported version is [{}].".format(  # noqa: E501
            report_path,
            version,
            __class__.C_MININAL_PYTEST_HTML_VERSION,
        )
        raise RuntimeError(err_msg)

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__json_blob_is_not_found(
        report_path: str,
    ) -> typing.NoReturn:
        assert report_path is not None

        err_msg = "Source file [{}] does not countains json data.".format(
            report_path,
        )
        raise RuntimeError(err_msg)


# //////////////////////////////////////////////////////////////////////////////


def main(arguments) -> int:
    has_errors = False

    # 1. Collect from positional files
    input_file = os.path.abspath(arguments.input)
    if not os.path.isfile(input_file):
        g_log.error(
            "Invalid input: '{}' is not a file or does not exist.".format(
                arguments.input,
            ),
        )
        has_errors = True

    # 2. Check output file
    if not arguments.replace and os.path.exists(arguments.out):
        g_log.error(
            "Invalid input: output file '{}' already exists.".format(
                arguments.out,
            ),
        )
        has_errors = True

    # 3. Final check
    if has_errors:
        g_log.error(
            "Termination due to input errors.",
        )
        return 1

    # Process each report file
    PytestHtmlJsonExtractor.exec(
        input_file,
        arguments.check_json,
        arguments.out,
        arguments.replace,
        arguments.unescape_logs,
    )

    g_log.info(
        "Successfully extracted json into {}".format(
            arguments.out,
        ),
    )
    return 0


# //////////////////////////////////////////////////////////////////////////////


def cli():
    arguments = parse_arguments()

    logging.basicConfig(level=int((6 - arguments.verbose) * 10))

    g_log.debug("opts = {}".format(arguments))

    r = main(arguments)

    g_log.debug("exiting")
    return r


# //////////////////////////////////////////////////////////////////////////////

if __name__ == "__main__":
    sys.exit(cli())

# //////////////////////////////////////////////////////////////////////////////
