# //////////////////////////////////////////////////////////////////////////////
from __future__ import annotations

import argparse
import bs4
import json
import logging
import os
import sys
import re
import typing

from . import __version__ as current_version

from packaging.version import Version

# //////////////////////////////////////////////////////////////////////////////

log = logging.getLogger(__name__)


# //////////////////////////////////////////////////////////////////////////////


def check_extension(
    file_direaction: str,
    choices: typing.List[str],
) -> typing.Callable:
    assert type(file_direaction) is str
    assert type(choices) is list

    def mapper(filename):
        ext = os.path.splitext(filename)[1].lower()
        if ext in choices:
            return filename
        raise argparse.ArgumentTypeError(
            "Bad {} file extension: '{}'. It was expecting one from {}.".format(
                file_direaction,
                ext,
                choices,
            )
        )

    return mapper


# ------------------------------------------------------------------------
def parse_arguments() -> argparse.Namespace:
    command_parser = argparse.ArgumentParser(
        description="A tool to extract json data from pytest-html report.",
        epilog="Example: pgpro-pytest-html-json-extract -o report.json report.html",
    )

    command_parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {current_version}",
        help="Show program's version number and exit",
    )

    command_parser.add_argument(
        "--out",
        "-o",
        help="name of the output json file",
        type=check_extension("output", [".json"]),
        required=True,
    )

    command_parser.add_argument(
        "--replace",
        "-r",
        help="replace output if it exists",
        action="store_true",
    )

    command_parser.add_argument(
        "--no-check-json",
        dest="check_json",
        action="store_false",
        help="skip JSON format validation after extraction",
    )

    command_parser.add_argument(
        "--verbose",
        "-v",
        help="level of logging verbosity",
        default=3,
        action="count",
    )

    command_parser.add_argument(
        "input",
        help="html file generated by pytest-html",
        type=check_extension("input", [".html", ".htm"]),
    )

    return command_parser.parse_args()


class PytestHtmlJsonExtractor:
    C_MININAL_PYTEST_HTML_VERSION = "4.0.2"

    # --------------------------------------------------------------------
    @staticmethod
    def _extract_pytest_html_version(
        report_path,
        report_soup: bs4.BeautifulSoup,
    ) -> str:
        assert report_path is not None
        assert isinstance(report_soup, bs4.BeautifulSoup)

        """
        Robustly extract pytest-html version from the report footer/header.
        Example text: '... by pytest-html v4.0.2'
        """
        link = report_soup.find("a", href=re.compile(r"pytest-html"))
        if link is None:
            raise RuntimeError(
                "Report does not have section with pytest-html link.",
            )

        parent_text = link.parent.get_text()

        # Looking for pattern 'v' and digits (v4.0.2)
        match = re.search(r"v(\d+\.\d+\.\d+[\w\.]*)", parent_text)
        if not match:
            __class__._raise_err__cant_extract_report_version(
                report_path,
                parent_text,
            )

        return match.group(1)

    # --------------------------------------------------------------------
    @staticmethod
    def exec(
        input_path: str,
        check_json: bool,
        output_path: str,
        replace: bool,
    ):
        assert type(input_path) is str
        assert type(check_json) is bool
        assert type(output_path) is str

        log.info("Processing report: {}".format(input_path))

        with open(input_path, "r", encoding="utf-8") as f:
            soup = bs4.BeautifulSoup(f, features="html.parser")

        html_version = __class__._extract_pytest_html_version(
            input_path,
            soup,
        )
        assert type(html_version) is str

        min_version = Version(__class__.C_MININAL_PYTEST_HTML_VERSION)
        if Version(html_version) < min_version:
            __class__._raise_err__unsupported_html_version(
                input_path,
                html_version,
            )

        # load json data from the current report
        containers = soup.select("#data-container")
        if not containers:
            __class__._raise_err__json_blob_is_not_found(input_path)

        report_data_container = containers[0]
        report_jsonblob = report_data_container.get("data-jsonblob")

        if report_jsonblob is None:
            __class__._raise_err__json_blob_is_not_found(
                input_path,
            )

        assert type(report_jsonblob) is str

        if check_json:
            log.info("Json data is checked...")
            json.loads(report_jsonblob)

        # write to file
        write_mode = "w" if replace else "x"

        with open(output_path, write_mode, encoding="utf-8") as f:
            f.write(report_jsonblob)

        return

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__no_section_with_version(report_path) -> typing.NoReturn:
        err_msg = "Report [{}] does not have section with pytest-html link.".format(  # noqa: E501
            report_path
        )
        raise RuntimeError(err_msg)

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__cant_extract_report_version(
        report_path,
        text,
    ) -> typing.NoReturn:
        assert report_path is not None
        err_msg = "Cannot extract pytest-html version from {0!r}. Source file is [{1}]".format(  # noqa: E501
            text,
            report_path,
        )
        raise RuntimeError(err_msg)

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__unsupported_html_version(
        report_path: str,
        version: str,
    ) -> typing.NoReturn:
        assert report_path is not None
        assert type(version) is str
        err_msg = "Source file [{}] has an unsupported version [{}]. The minimal supported version is [{}].".format(  # noqa: E501
            report_path,
            version,
            __class__.C_MININAL_PYTEST_HTML_VERSION,
        )
        raise RuntimeError(err_msg)

    # --------------------------------------------------------------------
    @staticmethod
    def _raise_err__json_blob_is_not_found(
        report_path: str,
    ) -> typing.NoReturn:
        assert report_path is not None

        err_msg = "Source file [{}] does not countains json data.".format(
            report_path,
        )
        raise RuntimeError(err_msg)


# //////////////////////////////////////////////////////////////////////////////


def main(arguments) -> int:
    has_errors = False

    # 1. Collect from positional files
    input_file = os.path.abspath(arguments.input)
    if not os.path.isfile(input_file):
        log.error(
            "Invalid input: '{}' is not a file or does not exist.".format(
                arguments.input,
            ),
        )
        has_errors = True

    # 2. Check output file
    if not arguments.replace and os.path.exists(arguments.out):
        log.error(
            "Invalid input: output file '{}' already exists.".format(
                arguments.out,
            ),
        )
        has_errors = True

    # 3. Final check
    if has_errors:
        log.error(
            "Termination due to input errors.",
        )
        return 1

    # Process each report file
    PytestHtmlJsonExtractor.exec(
        input_file,
        arguments.check_json,
        arguments.out,
        arguments.replace,
    )

    log.info(
        "Successfully extracted json into {}".format(
            arguments.out,
        ),
    )
    return 0


# //////////////////////////////////////////////////////////////////////////////


def cli():
    arguments = parse_arguments()

    logging.basicConfig(level=int((6 - arguments.verbose) * 10))

    log.debug("opts = {}".format(arguments))

    r = main(arguments)

    log.debug("exiting")
    return r


# //////////////////////////////////////////////////////////////////////////////

if __name__ == "__main__":
    sys.exit(cli())

# //////////////////////////////////////////////////////////////////////////////
